(()=>{
const editStyle=document.createElement('style');editStyle.textContent='.admin-edit-field{display:grid;gap:6px}.admin-edit-field input,.admin-edit-field select,.admin-edit-field textarea{width:100%;min-height:44px;padding:10px 12px;border:1px solid #d7e0d6;border-radius:9px;background:#fbfcf9;font:inherit}.admin-edit-field textarea{min-height:100px;resize:vertical}.edit-help{color:var(--muted)}@media(min-width:700px){.admin-edit-field.wide{grid-column:1/-1}}';document.head.append(editStyle);
const cfg=window.AGRI_CONFIG||{},configured=!cfg.SUPABASE_URL?.includes('YOUR_PROJECT'),login=document.querySelector('#loginPanel'),dash=document.querySelector('#dashboard'),status=document.querySelector('#adminStatus'),wrap=document.querySelector('#submissions'),dlg=document.querySelector('#reviewDialog'),review=document.querySelector('#reviewBody');let db,rows=[],current=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={pending:'بانتظار المراجعة',approved:'منشور',rejected:'مرفوض',archived:'مؤرشف'};
const categories=[['','تلقائي حسب نوع النشاط'],['farm','المزارع'],['nursery','المشاتل'],['laboratory','المختبرات'],['supplies','المستلزمات والمعدات'],['irrigation','الري والمياه'],['organization','الجمعيات والمنظمات'],['food','التصنيع الغذائي'],['services','الخدمات والاستشارات']];
const editFields=[['name','اسم المؤسسة','text'],['business_types','نوع النشاط','array'],['description','الوصف','textarea'],['year_established','سنة التأسيس','text'],['employees','عدد العاملين','text'],['governorate','المحافظة','text'],['district','القضاء','text'],['town','البلدة','text'],['address','العنوان','text'],['map_url','رابط الخريطة','url'],['contact_name','الشخص المسؤول','text'],['position','الصفة','text'],['phone','الهاتف','text'],['whatsapp','واتساب','text'],['email','البريد الإلكتروني','email'],['website','الموقع الإلكتروني','text'],['facebook','Facebook','text'],['instagram','Instagram','text'],['products_services','المنتجات والخدمات','array'],['crops','المحاصيل والقطاعات','array'],['details','تفاصيل إضافية','textarea'],['logo_url','رابط الشعار','url'],['main_photo_url','رابط الصورة الرئيسية','url'],['additional_photos','روابط صور إضافية','array'],['areas_served','المناطق المخدومة','array'],['delivery','التوصيل','text'],['service_outside','خدمات خارج المنطقة','text'],['online_available','بيع عبر الإنترنت','text'],['store_url','رابط المتجر','url']];
const valueOf=(r,key)=>Array.isArray(r[key])?r[key].join('\n'):(r[key]??'');
function renderStats(){document.querySelector('#stats').innerHTML=['pending','approved','rejected','archived'].map(s=>`<div class="stat"><b>${rows.filter(r=>r.status===s).length}</b><span>${labels[s]}</span></div>`).join('')}
function render(){const q=document.querySelector('#adminSearch').value.toLowerCase(),f=document.querySelector('#statusFilter').value,out=rows.filter(r=>(!f||r.status===f)&&[r.name,r.governorate,r.district,r.email,r.phone].join(' ').toLowerCase().includes(q));wrap.innerHTML=out.map(r=>`<article class="submission"><div><h3>${esc(r.name)}</h3><div class="meta">${esc([r.governorate,r.district,r.town].filter(Boolean).join('، '))} · ${esc(r.created_at?.slice(0,10))}</div><span class="pill ${r.status}">${labels[r.status]||r.status}</span></div><div class="submission-actions"><button class="btn btn-light" data-open="${r.id}">عرض وتعديل</button><button class="btn btn-approve" data-status="approved" data-id="${r.id}">نشر</button><button class="btn btn-reject" data-status="rejected" data-id="${r.id}">رفض</button></div></article>`).join('');status.textContent=out.length?'':'لا توجد طلبات مطابقة.'}
async function load(){status.textContent='جاري تحميل الطلبات…';const{data,error}=await db.from('listings').select('*').order('created_at',{ascending:false});if(error){status.textContent='غير مخوّل بعرض البيانات أو تعذّر الاتصال.';return}rows=data||[];status.textContent='';renderStats();render()}
async function setStatus(id,value,notes){const patch={status:value,updated_at:new Date().toISOString()};if(notes!==undefined)patch.reviewer_notes=notes;const{error}=await db.from('listings').update(patch).eq('id',id);if(error){alert('تعذّر حفظ القرار.');return}await load();if(dlg.open)dlg.close()}
function editorField(r,[key,label,type]){const value=esc(valueOf(r,key)),wide=['description','business_types','products_services','crops','details','additional_photos','areas_served'].includes(key)?'wide':'';if(type==='textarea'||type==='array')return`<label class="admin-edit-field ${wide}"><b>${label}</b><textarea data-field="${key}" ${type==='array'?'data-array="true"':''}>${value}</textarea></label>`;return`<label class="admin-edit-field ${wide}"><b>${label}</b><input data-field="${key}" type="${type}" value="${value}"></label>`}
function openReview(r){current=r;review.innerHTML=`<h2>${esc(r.name)}</h2><p class="edit-help">يمكن تعديل البيانات أدناه. افصل العناصر المتعددة بسطر جديد أو فاصلة.</p><div class="review-grid"><label class="admin-edit-field wide"><b>فئة الدليل</b><select id="directoryCategory">${categories.map(([v,l])=>`<option value="${v}" ${r.directory_category===v?'selected':''}>${l}</option>`).join('')}</select></label>${editFields.map(f=>editorField(r,f)).join('')}</div><label class="admin-edit-field wide"><b>ملاحظات الإدارة</b><textarea id="notes">${esc(r.reviewer_notes||'')}</textarea></label><label class="check"><input id="verifiedFlag" type="checkbox" ${r.verified?'checked':''}> توثيق المؤسسة</label><div class="review-actions"><button class="btn btn-primary" id="saveListing">حفظ التعديلات</button><button class="btn btn-approve" data-decision="approved">حفظ ونشر</button><button class="btn btn-reject" data-decision="rejected">رفض</button><button class="btn btn-light" data-decision="archived">أرشفة</button></div><p id="saveMessage" class="status"></p>`;dlg.showModal()}
function collectEdit(){const patch={directory_category:document.querySelector('#directoryCategory').value||null,verified:document.querySelector('#verifiedFlag').checked,reviewer_notes:document.querySelector('#notes').value,updated_at:new Date().toISOString()};review.querySelectorAll('[data-field]').forEach(el=>{let v=el.value.trim();if(el.dataset.array)v=v.split(/[,،\n]/).map(x=>x.trim()).filter(Boolean);patch[el.dataset.field]=v||null});return patch}
async function saveEdit(close=false){const msg=document.querySelector('#saveMessage');msg.textContent='جاري الحفظ…';const{error}=await db.from('listings').update(collectEdit()).eq('id',current.id);if(error){msg.textContent='تعذّر حفظ التعديلات.';return false}msg.textContent='تم حفظ التعديلات بنجاح.';await load();if(close)dlg.close();return true}
async function showDashboard(session){login.hidden=true;dash.hidden=false;document.querySelector('#adminEmail').textContent=session.user.email;await load()}
async function boot(){if(!configured){document.querySelector('#loginError').textContent='يلزم ربط Supabase أولاً.';return}db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const{data}=await db.auth.getSession();if(data.session)showDashboard(data.session)}
document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();if(!configured)return;const{data,error}=await db.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});document.querySelector('#loginError').textContent=error?'بيانات الدخول غير صحيحة.':'';if(data.session)showDashboard(data.session)};
document.querySelector('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};['adminSearch','statusFilter'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));wrap.onclick=e=>{const o=e.target.closest('[data-open]'),s=e.target.closest('[data-status]');if(o)openReview(rows.find(r=>r.id===o.dataset.open));if(s)setStatus(s.dataset.id,s.dataset.status)};
review.onclick=async e=>{if(e.target.closest('#saveListing')){await saveEdit();return}const b=e.target.closest('[data-decision]');if(!b)return;const ok=await saveEdit();if(ok)setStatus(current.id,b.dataset.decision,document.querySelector('#notes').value)};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('#exportCsv').onclick=()=>{const cols=['name','status','directory_category','governorate','district','town','phone','email','created_at'],csv=[cols.join(','),...rows.map(r=>cols.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='agri-directory.csv';a.click()};boot()})();
