(()=>{
const style=document.createElement('style');style.textContent=`.admin-edit-field{display:grid;gap:6px}.admin-edit-field input,.admin-edit-field select,.admin-edit-field textarea{width:100%;min-height:44px;padding:10px 12px;border:1px solid #d7e0d6;border-radius:9px;background:#fbfcf9;font:inherit}.admin-edit-field textarea{min-height:100px;resize:vertical}.edit-help{color:var(--muted)}.category-admin{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;padding:14px;border:1px solid var(--line);border-radius:12px}.category-admin label{display:flex;align-items:center;gap:7px}.category-admin input{width:auto}.owner-panel,.media-panel{margin:14px 0;padding:16px;border-radius:14px;background:#eef6ee}.owner-panel h3,.media-panel h3{margin-top:0}.owner-actions{display:flex;gap:8px;flex-wrap:wrap}.admin-media{display:flex;gap:12px;flex-wrap:wrap}.admin-media img{display:block;width:110px;height:90px;object-fit:contain;background:#fff;border:1px solid var(--line);border-radius:10px}.admin-section{margin-top:18px}.admin-section h3{border-bottom:1px solid var(--line);padding-bottom:8px}.quick-wa{color:#17613c;font-weight:700;text-decoration:none}@media(min-width:700px){.admin-edit-field.wide{grid-column:1/-1}}@media(max-width:700px){.category-admin{grid-template-columns:1fr}}`;document.head.append(style);
const cfg=window.AGRI_CONFIG||{},configured=!cfg.SUPABASE_URL?.includes('YOUR_PROJECT'),login=document.querySelector('#loginPanel'),dash=document.querySelector('#dashboard'),status=document.querySelector('#adminStatus'),wrap=document.querySelector('#submissions'),dlg=document.querySelector('#reviewDialog'),review=document.querySelector('#reviewBody');let db,rows=[],current=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),wa=n=>String(n||'').replace(/\D/g,'');
const labels={pending:'بانتظار المراجعة',approved:'منشور',rejected:'مرفوض',archived:'مؤرشف'};
const categories=[['farm','المزارع'],['nursery','المشاتل'],['laboratory','المختبرات'],['supplies','المستلزمات والمعدات'],['irrigation','الري والمياه'],['organization','الجمعيات والمنظمات'],['food','التصنيع الغذائي'],['services','الخدمات والاستشارات']];
const sections=[
['المؤسسة',[['name','اسم المؤسسة','text'],['business_types','أنواع النشاط التفصيلية','array'],['description','الوصف','textarea'],['year_established','سنة التأسيس','text'],['employees','عدد العاملين','text'],['details','تفاصيل إضافية','textarea']]],
['المالك والإدارة',[['owner_name','اسم صاحب/مالكة المؤسسة','text'],['owner_whatsapp','WhatsApp المالك','text'],['managed_by_engineer','تُدار من مهندس زراعي','boolean'],['engineer_name','اسم المهندس/ة الزراعي/ة','text']]],
['الموقع',[['governorate','المحافظة','text'],['district','القضاء','text'],['town','البلدة','text'],['address','العنوان','text'],['map_url','رابط الخريطة','url'],['multiple_locations','فروع متعددة','text']]],
['التواصل',[['contact_name','مسؤول التواصل','text'],['position','الصفة','text'],['phone','الهاتف العام','text'],['whatsapp','WhatsApp العام','text'],['email','البريد الإلكتروني','email'],['website','الموقع الإلكتروني','text'],['facebook','Facebook','text'],['instagram','Instagram','text']]],
['الخدمات',[['products_services','المنتجات والخدمات','array'],['crops','المحاصيل والاختصاصات','array'],['areas_served','المناطق المخدومة','array'],['works_directly','تعامل مباشر مع المزارعين','text'],['delivery','التوصيل','text'],['service_outside','خدمات خارج المنطقة','text'],['online_available','بيع عبر الإنترنت','text'],['store_url','رابط المتجر','url']]],
['الصور والشعارات',[['logo_url','رابط الشعار','url'],['main_photo_url','رابط الصورة الرئيسية','url'],['additional_photos','روابط الصور الإضافية','array']]]];
const valueOf=(r,key)=>Array.isArray(r[key])?r[key].join('\n'):(r[key]??'');
function selectedCategories(r){const cats=Array.isArray(r.directory_categories)?r.directory_categories.filter(v=>categories.some(c=>c[0]===v)):[];if(!cats.length&&r.directory_category)cats.push(r.directory_category);return cats}
function renderStats(){document.querySelector('#stats').innerHTML=['pending','approved','rejected','archived'].map(s=>`<div class="stat"><b>${rows.filter(r=>r.status===s).length}</b><span>${labels[s]}</span></div>`).join('')}
function render(){const q=document.querySelector('#adminSearch').value.toLowerCase(),f=document.querySelector('#statusFilter').value,out=rows.filter(r=>(!f||r.status===f)&&[r.name,r.owner_name,r.contact_name,r.governorate,r.district,r.email,r.phone,r.owner_whatsapp].join(' ').toLowerCase().includes(q));wrap.innerHTML=out.map(r=>`<article class="submission"><div><h3>${esc(r.name)}</h3><div class="meta">${esc([r.governorate,r.district,r.town].filter(Boolean).join('، '))} · ${esc(r.created_at?.slice(0,10))}</div><div class="meta">المالك: ${esc(r.owner_name||'غير مسجل')} ${r.owner_whatsapp?`· <a class="quick-wa" target="_blank" rel="noopener" href="https://wa.me/${wa(r.owner_whatsapp)}">WhatsApp</a>`:''}</div><span class="pill ${r.status}">${labels[r.status]||r.status}</span></div><div class="submission-actions"><button class="btn btn-light" data-open="${r.id}">إدارة كاملة</button><button class="btn btn-approve" data-status="approved" data-id="${r.id}">نشر</button><button class="btn btn-reject" data-status="rejected" data-id="${r.id}">رفض</button></div></article>`).join('');status.textContent=out.length?'':'لا توجد طلبات مطابقة.'}
async function load(){status.textContent='جاري تحميل الطلبات…';const{data,error}=await db.from('listings').select('*').order('created_at',{ascending:false});if(error){status.textContent='غير مخوّل بعرض البيانات أو تعذّر الاتصال.';return}rows=data||[];status.textContent='';renderStats();render()}
async function setStatus(id,value,notes){const patch={status:value,updated_at:new Date().toISOString()};if(notes!==undefined)patch.reviewer_notes=notes;const{error}=await db.from('listings').update(patch).eq('id',id);if(error){alert('تعذّر حفظ القرار.');return}await load();if(dlg.open)dlg.close()}
function editorField(r,[key,label,type]){const value=esc(valueOf(r,key)),wide=['description','business_types','products_services','crops','details','additional_photos','areas_served'].includes(key)?'wide':'';if(type==='boolean')return`<label class="check admin-edit-field ${wide}"><input data-field="${key}" data-boolean="true" type="checkbox" ${r[key]?'checked':''}> ${label}</label>`;if(type==='textarea'||type==='array')return`<label class="admin-edit-field ${wide}"><b>${label}</b><textarea data-field="${key}" ${type==='array'?'data-array="true"':''}>${value}</textarea></label>`;return`<label class="admin-edit-field ${wide}"><b>${label}</b><input data-field="${key}" type="${type}" value="${value}"></label>`}
function imagePreview(r){const images=[['الشعار',r.logo_url],['الصورة الرئيسية',r.main_photo_url],...(Array.isArray(r.additional_photos)?r.additional_photos.map((u,i)=>[`صورة ${i+1}`,u]):[])].filter(x=>x[1]);return images.length?`<div class="media-panel"><h3>معاينة الصور والشعارات</h3><div class="admin-media">${images.map(([l,u])=>`<a href="${esc(u)}" target="_blank" rel="noopener"><img src="${esc(u)}" alt="${esc(l)}" onerror="this.closest('a').style.display='none'"><small>${esc(l)}</small></a>`).join('')}</div></div>`:''}
function openReview(r){current=r;const cats=selectedCategories(r);review.innerHTML=`<h2>${esc(r.name)}</h2><p class="edit-help">يمكن تعديل كل المعلومات. الحقول المتعددة تُفصل بسطر جديد أو فاصلة.</p><div class="owner-panel"><h3>اتصال سريع بالمالك</h3><p><b>${esc(r.owner_name||'لم يُسجل اسم المالك بعد')}</b> ${r.owner_whatsapp?`· ${esc(r.owner_whatsapp)}`:''}</p><div class="owner-actions">${r.owner_whatsapp?`<a class="btn btn-approve" href="https://wa.me/${wa(r.owner_whatsapp)}" target="_blank" rel="noopener">فتح WhatsApp المالك</a>`:''}${r.whatsapp?`<a class="btn btn-light" href="https://wa.me/${wa(r.whatsapp)}" target="_blank" rel="noopener">WhatsApp المؤسسة</a>`:''}${r.email?`<a class="btn btn-light" href="mailto:${esc(r.email)}">إرسال بريد</a>`:''}</div></div><div class="admin-section"><h3>فئات الظهور في الدليل</h3><div class="category-admin">${categories.map(([v,l])=>`<label><input type="checkbox" data-category="${v}" ${cats.includes(v)?'checked':''}> ${l}</label>`).join('')}</div></div>${sections.map(([title,fields])=>`<section class="admin-section"><h3>${title}</h3><div class="review-grid">${fields.map(f=>editorField(r,f)).join('')}</div></section>`).join('')}${imagePreview(r)}<label class="admin-edit-field wide"><b>ملاحظات الإدارة (داخلية)</b><textarea id="notes">${esc(r.reviewer_notes||'')}</textarea></label><label class="check"><input id="verifiedFlag" type="checkbox" ${r.verified?'checked':''}> توثيق المؤسسة</label><div class="review-actions"><button class="btn btn-primary" id="saveListing">حفظ التعديلات</button><button class="btn btn-approve" data-decision="approved">حفظ ونشر</button><button class="btn btn-reject" data-decision="rejected">حفظ ورفض</button><button class="btn btn-light" data-decision="archived">حفظ وأرشفة</button></div><p id="saveMessage" class="status"></p>`;dlg.showModal()}
function collectEdit(){const cats=[...review.querySelectorAll('[data-category]:checked')].map(el=>el.dataset.category),patch={directory_categories:cats,directory_category:cats[0]||null,verified:document.querySelector('#verifiedFlag').checked,reviewer_notes:document.querySelector('#notes').value,updated_at:new Date().toISOString()};review.querySelectorAll('[data-field]').forEach(el=>{let v=el.dataset.boolean?el.checked:el.value.trim();if(el.dataset.array)v=v.split(/[,،\n]/).map(x=>x.trim()).filter(Boolean);patch[el.dataset.field]=v===''?null:v});return patch}
async function saveEdit(){const msg=document.querySelector('#saveMessage');msg.textContent='جاري الحفظ…';const{error}=await db.from('listings').update(collectEdit()).eq('id',current.id);if(error){msg.textContent='تعذّر حفظ التعديلات: '+error.message;return false}msg.textContent='تم حفظ كل التعديلات بنجاح.';await load();return true}
async function showDashboard(session){login.hidden=true;dash.hidden=false;document.querySelector('#adminEmail').textContent=session.user.email;await load()}
async function boot(){if(!configured){document.querySelector('#loginError').textContent='يلزم ربط Supabase أولاً.';return}db=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const{data}=await db.auth.getSession();if(data.session)showDashboard(data.session)}
document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();if(!configured)return;const{data,error}=await db.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});document.querySelector('#loginError').textContent=error?'بيانات الدخول غير صحيحة.':'';if(data.session)showDashboard(data.session)};
document.querySelector('#signOut').onclick=async()=>{await db.auth.signOut();location.reload()};['adminSearch','statusFilter'].forEach(id=>document.querySelector('#'+id).addEventListener('input',render));wrap.onclick=e=>{const o=e.target.closest('[data-open]'),s=e.target.closest('[data-status]');if(o)openReview(rows.find(r=>r.id===o.dataset.open));if(s)setStatus(s.dataset.id,s.dataset.status)};
review.onclick=async e=>{if(e.target.closest('#saveListing')){await saveEdit();return}const b=e.target.closest('[data-decision]');if(!b)return;const notes=document.querySelector('#notes').value,ok=await saveEdit();if(ok)setStatus(current.id,b.dataset.decision,notes)};
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelector('#exportCsv').onclick=()=>{const cols=['name','status','directory_categories','owner_name','owner_whatsapp','managed_by_engineer','engineer_name','contact_name','governorate','district','town','phone','whatsapp','email','website','created_at'],csv=[cols.join(','),...rows.map(r=>cols.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='agri-directory-full.csv';a.click()};boot()})();
